### ISSUE TITLE
Forge Server won't start with only this mod

### ISSUE THREAD

**Issue by orionSquared** [thomasglasser/Sherds-API#4]
So I'm working on building a modpack and I'm running into a weird crash but only on servers. This mod seems to be causing an issue. I'm using the 4.0.3 version of the mod. I did notice the file says neoforge, but it's been working fine client-side. But when I tried to put it on a server, the server crashes with an error code 1. There's no crash log that generates. 

I tried removing every other mod and tried to only launch the server with only this mod, just the API. Same crash.

**Comment by thomasglasser** [comment]
Attach the latest.log file generated in the logs folder

**Comment by thomasglasser** [comment]
Also, the mod won't work client-side, it must be present on both sides, but it should be compatible with old Forge still

**Comment by drakray** [comment]
I have the same problem with NeoForge 47.1.79, can't boot my dedicated server with SherdAPI, removing it(and moreSherd), allow theserver to boot

**Comment by thomasglasser** [comment]
A crash log would help

**Comment by drakray** [comment]
I'll get you one tommorrow with the bare minimum(too many mods and the crash becomes unreadable)

**Comment by drakray** [comment]
[latest.log](https://github.com/thomasglasser/Sherds-API/files/13338809/latest.log)
[debug.log](https://github.com/thomasglasser/Sherds-API/files/13338810/debug.log)

Minecraft 1.20.1
Neoforge 47.1.79
SherdAPI 4.0.3
As server, No other mods, using Java 17 (```"C:\Program Files\Java\jdk-17\bin\javaw.exe"```)
